const allInterests = [
  "Premier League (IPL)",
  "Cricket Team",
  "Cricket Tournaments",
  "Movies",
  "Celebrities",
  "Film Awards",
  "Film Festivals",
  "Narendra Modi",
  "National Congress (INC)",
  "State Elections",
  "Regional Cuisine",
  "Street Food",
  "Cooking Shows",
  "Traditional Wear",
  "Fashion Weeks",
  "Fashion Trends",
  "Destinations",
  "Heritage Sites",
  "Adventure Tourism",
  "Tech Startups",
  "IT Companies",
  "Digital Initiatives",
  "Ayurveda",
  "Hospitals",
  "Health Insurance",
  "Economy",
  "Startups",
  "Entrepreneurship",
  "Classical Dance",
  "Folk Art",
  "Cultural Festivals",
  "Space Research Organisation (ISRO)",
  "Science Research",
  "Innovations",
  "Universities",
  "Educational Reforms",
  "Education News",
  "Authors",
  "Literary Festivals",
  "Poetry",
  "Diwali",
  "Holi",
  "Eid",
  "Navratri",
  "Environmental Issues",
  "Wildlife Conservation",
  "Renewable Energy",
  "Ancient History",
  "Historical Sites",
  "Museums",
  "Parenting Tips",
  "Child Development",
  "Family Values",
  "Handicrafts",
  "DIY Projects",
  "Craft Workshops",
  "Interior Design",
  "Home Improvement",
  "Automobile Industry",
  "Car Reviews",
  "Road Safety",
  "Music Genres",
  "Artists",
  "Music Festivals",
  "Video Games",
  "Esports",
  "Gaming News",
  "Books",
  "Writing Tips",
  "Author Interviews",
  "Workout Routines",
  "Gym Motivation",
  "Fitness Challenges",
  "Self-Care Tips",
  "Mindfulness",
  "Stress Management",
  "Travel Hacks",
  "Budget Travel",
  "Solo Travel Tips",
  "AI",
  "Blockchain",
  "IoT",
  "Digital Transformation",
  "Climate Change",
  "Conservation Efforts",
  "Green Living",
  "Political News",
  "Elections",
  "Policy Debates",
  "Budgeting",
  "Saving Tips",
  "Financial Planning",
  "Cooking Techniques",
  "Recipe Ideas",
  "Culinary Inspiration",
  "Movie Reviews",
  "Director Interviews",
  "Film Festivals",
  "Fashion Shows",
  "Designer Collections",
  "Style Inspiration",
  "Jokes",
  "Stand-Up Comedy",
  "Funny Memes",
  "Parenting Hacks",
  "Child Development Milestones",
  "Art Exhibitions",
  "Design Trends",
  "Creative Inspiration",
  "Home DIY",
  "Craft Tutorials",
  "DIY Hacks",
  "Housing Market Trends",
  "Home Buying Tips",
  "Pet Health",
  "Training Tips",
  "Pet Adoption",
  "Love Advice",
  "Dating Etiquette",
  "Relationship Goals",
];

export default allInterests;
